<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="1MG-LPTP-260" failures="0" tests="2" name="Default test" time="14.813" errors="0" timestamp="17 Jun 2018 07:38:11 GMT">
  <testcase classname="tests.TestProfileAndLock" name="@BeforeClass verifyLogin" time="1.899">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at tests.TestProfileAndLock.verifyLogin(TestProfileAndLock.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeClass verifyLogin -->
  <testcase classname="baseTests.BaseClass" name="@BeforeMethod createReportLogger" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod createReportLogger -->
  <testcase classname="baseTests.BaseClass" name="@AfterMethod captureStatus" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod captureStatus -->
  <testcase classname="baseTests.BaseClass" name="@BeforeMethod createReportLogger" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod createReportLogger -->
  <testcase classname="baseTests.BaseClass" name="@AfterMethod captureStatus" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod captureStatus -->
  <testcase classname="baseTests.BaseClass" name="@AfterTest tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase classname="tests.TestProfileAndLock" name="checkAccountLock" time="0.0">
    <skipped/>
  </testcase> <!-- checkAccountLock -->
  <testcase classname="tests.TestProfileAndLock" name="verifyProfilePage" time="0.0">
    <skipped/>
  </testcase> <!-- verifyProfilePage -->
</testsuite> <!-- Default test -->
